/*EJERCICIO 1*/
SELECT *
FROM PRODUCTOS
WHERE TIPO IN ('A') AND PVP> 20
ORDER BY CODPRODUCTO;
/*EJERCICIO 2*/
SELECT DISTINCT(TIPO), SUM(DISTINCT(STOCK)) TOTAL
FROM PRODUCTOS
GROUP BY TIPO, STOCK;
/*EJERCICIO 3*/
SELECT CODPRODUCTO, DENOMINACION
FROM PRODUCTOS
WHERE CODPRODUCTO NOT IN (SELECT CODPRODUCTO FROM DETCOMPRAS);
/*EJERCICIO 4*/
SELECT CODCLIENTE, NOMBRE
FROM CLIENTES 
WHERE POBLACION LIKE 'MADRID' AND CODCLIENTE IN (SELECT CODCLIENTE FROM COMPRAS
WHERE NUMCOMPRA IN (SELECT NUMCOMPRA FROM DETCOMPRAS
WHERE CODPRODUCTO IN (SELECT CODPRODUCTO FROM PRODUCTOS 
WHERE TIPO LIKE 'A'))) 
ORDER BY CODCLIENTE;
/*EJERCICIO 5*/
SELECT *
FROM PRODUCTOS
WHERE PVP >= 30 AND CODPRODUCTO IN (SELECT CODPRODUCTO FROM DETCOMPRAS 
WHERE NUMCOMPRA IN (SELECT NUMCOMPRA FROM COMPRAS 
WHERE CODCLIENTE IN (SELECT CODCLIENTE FROM CLIENTES
WHERE POBLACION LIKE 'TALAVERA')));
/*EJERCICIO 6*/
SELECT S.NUMCOMPRA, S.FECHA, C.CODCLIENTE, C.NOMBRE
FROM COMPRAS S JOIN CLIENTES C ON (S.CODCLIENTE=C.CODCLIENTE)
WHERE POBLACION IN ('MADRID') AND (FECHA>='01/01/24' AND FECHA<='31/03/24' )
ORDER BY NUMCOMPRA, CODCLIENTE;
/*EJERCICIO 7*/
SELECT C.CODCLIENTE, C.NOMBRE, S.NUMCOMPRA, SUM(D.UNIDADES)
FROM CLIENTES C JOIN COMPRAS S ON (S.CODCLIENTE=C.CODCLIENTE)
JOIN DETCOMPRAS D ON(S.NUMCOMPRA=D.NUMCOMPRRA)
WHERE ;
/*EJERCICIO 8*/
SELECT P.CODPRODUCTO ,P.DENOMINACION ,P.TIPO ,P.PVP ,SUM(D.UNIDADES) "UNIDADES", SUM(P.PVP) "IMPORTE TOTAL", 
P.STOCK-SUM(D.UNIDADES) "STOCK ACTUAL"
FROM PRODUCTOS P JOIN DETCOMPRAS D ON (P.CODPRODUCTO=D.CODPRODUCTO)
WHERE P.CODPRODUCTO IN (SELECT CODPRODUCTO FROM DETCOMPRAS)
GROUP BY P.CODPRODUCTO ,P.DENOMINACION ,P.TIPO ,P.PVP ,D.UNIDADES , P.PVP, 
P.STOCK, D.UNIDADES;
/*EJERCICIO 9*/
SELECT P.STOCK-SUM(D.UNIDADES) "STOCK_ACTUAL"
FROM PRODUCTOS P JOIN DETCOMPRAS D ON (P.CODPRODUCTO=D.CODPRODUCTO)
WHERE P.STOCK-SUM(D.UNIDADES) < 0
GROUP BY STOCK, UNIDADES;
/*EJERCICIO 10 SOLO PUEDE HABER UN PRODUCTO CON EL MINIMO DE PRECIO*/
SELECT C.CODCLIENTE, C.NOMBRE, P.CODPRODUCTO, P.DENOMINACION
FROM CLIENTES C JOIN COMPRAS S ON (C.CODCLIENTE=S.CODCLIENTE)
JOIN DETCOMPRAS D ON (S.NUMCOMPRA=D.NUMCOMPRA)
JOIN PRODUCTOS P ON (D.CODPRODUCTO=P.CODPRODUCTO)
WHERE PVP IN(SELECT MIN(PVP) FROM PRODUCTOS)
ORDER BY C.CODCLIENTE;
/*EJERCICIO 11 SOLO PUEDE HABER UN PRODUCTO CON MAXIMO DE UNIDADES*/
SELECT P.CODPRODUCTO, P.DENOMINACION, P.TIPO, P.PVP, SUM(DISTINCT(D.UNIDADES))
FROM PRODUCTOS P JOIN DETCOMPRAS D ON (P.CODPRODUCTO=D.CODPRODUCTO)
WHERE D.UNIDADES IN (SELECT MAX(DISTINCT(UNIDADES)) FROM DETCOMPRAS)
GROUP BY P.CODPRODUCTO, P.DENOMINACION, P.TIPO, P.PVP, D.UNIDADES;
/*EJERCICIO 12*/
SELECT CODPRODUCTO, PVP, TIPO,
DECODE(RTRIM(TIPO), 'A',21,'B',10,'C',4)IVA, 
DECODE(RTRIM(TIPO), 'A',((PVP*21)/100),'B',((PVP*10)/100),'C',((PVP*4)/100)) "IVA CALCULADO",
DECODE(RTRIM(TIPO), 'A',(PVP+((PVP*21)/100)),'B',(PVP+((PVP*10)/100)),'C',(PVP+((PVP*4)/100))) "PRECIO MAS IVA"
FROM PRODUCTOS;
/*EJERCICIO 14*/
SELECT C.CODCLIENTE, C.NOMBRE, D.UNIDADES
FROM CLIENTES C JOIN COMPRAS S ON (C.CODCLIENTE=S.CODCLIENTE)
JOIN DETCOMPRAS D ON (S.NUMCOMPRA=D.NUMCOMPRA)
WHERE UNIDADES IN (SELECT MAX(UNIDADES) FROM DETCOMPRAS);
