/*EJ 4*/
INSERT  INTO PEDIDOS
SELECT '0001-T' , COD_ARTICULO, SYSDATE, 100
FROM VENTAS
WHERE UNIDADES_VENDIDAS = (SELECT MAX (UNIDADES_VENDIDAS)
FROM VENTAS);

/*EJ 5*/
INSERT INTO PEDIDOS
SELECT '0001-T', COD_ARTICULO, SYSDATE, 100
FROM VENTAS
GROUP BY COD_ARTICULO
HAVING COUNT (*) = (SELECT MAX (COUNT (UNIDADES_VENDIDAS))
FROM VENTAS
GROUP BY COD_ARTICULO);

/*EJ 6*/
INSERT INTO PEDIDOS
VALUES (
(SELECT COD_TIENDA FROM TIENDAS WHERE NOMBRE LIKE 'La gacela'),
(SELECT COD_ARTICULO FROM ARTICULOS WHERE NOM_ARTICULO LIKE 'Mantequilla'),
SYSDATE +15,
(SELECT AVG (UNIDADES_VENDIDAS) FROM VENTAS)
);

/*EJ 7*/
/*INSERT INTO PEDIDOS
SELECT '0006-T', COD_ARTICULO, TO_DATE (SYSDATE) +7, 35
FROM VENTAS
GROUP BY COD_ARTICULO
HAVING SUM (UNIDADES_VENDIDAS) >10;*/

/*EJ 8*/
UPDATE TIENDAS SET DIRECCION = 'C. Pilar, 7', POBLACION = 'Talavera de la Reina', CODPOSTAL=45600
WHERE NOMBRE LIKE 'Ultramarinos Montse';
/*ej 9*/
UPDATE ARTICULOS SET CATEGORIA='Segunda'
WHERE CATEGORIA='Primera' AND
COD_FABRICANTE IN (SELECT COD_FABRICANTE
FROM FABRICANTES
WHERE UPPER(PAIS)='ITALIA');

/*EJ 10*/
UPDATE TIENDAS
SET (NOMBRE, DIRECCION, POBLACION, PROVINCIA, CODPOSTAL)
=(SELECT NOMBRE, DIRECCION, POBLACION, PROVINCIA, CODPOSTAL
FROM TIENDAS
WHERE NOMBRE LIKE 'La Pasta Gansa')
WHERE NOMBRE LIKE 'Comestibles Rodolfo';
/*EJ 11*/
UPDATE ARTICULOS SET PRECIO_ACTUAL=PRECIO_ACTUAL*0.9
WHERE COD_ARTICULO NOT IN (SELECT COD_ARTICULO FROM VENTAS);
/*EJ 12*/
UPDATE PEDIDOS P SET UNIDADES_PEDIDAS =
(SELECT EXISTENCIAS *0.80
FROM ARTICULOS
WHERE COD_ARTICULO = P.COD_ARTICULO)
WHERE UNIDADES_PEDIDAS <
(SELECT EXISTENCIAS
FROM ARTICULOS
WHERE COD_ARTICULO = P.COD_ARTICULO);

/*EJ 13*/
UPDATE ARTICULOS A SET EXISTENCIAS = EXISTENCIAS
+
(SELECT NVL (SUM (UNIDADES_VENDIDAS), 0)
FROM VENTAS
WHERE COD_ARTICULO = A.COD_ARTICULO)
-
(SELECT NVL (SUM (UNIDADES_PEDIDAS),0)
FROM PEDIDOS
WHERE COD_ARTICULO = A.COD_ARTICULO);

/*EJ 14*/
INSERT INTO TIENDAS
VALUES ((SELECT TRIM(TO_CHAR(MAX(SUBSTR(COD_TIENDA,1, INSTR(COD_TIENDA, '_')-1))+1, '0000')) || '-1' FROM TIENDAS),
'Hueveria Ferreteria el Martillo', 'C. Leopoldo Panero, 4', 'LEÓN', 'LEÓN', 24001);

/*EJ 15*/
INSERT INTO PEDIDOS
(SELECT
(SELECT COD_TIENDA FROM TIENDAS WHERE NOMBRE LIKE 'Hueveria Ferreteria el Martillo'),
COD_ARTICULO, 
SYSDATE,
DECODE (CATEGORIA,
'Primera',
(SELECT AVG(UNIDADES_VENDIDAS) * 4
FROM VENTAS JOIN ARTICULOS USING (COD_ARTICULO)
WHERE CATEGORIA LIKE 'Primera'),
'Segunda',
(SELECT AVG (UNIDADES_VENDIDAS) *3
FROM VENTAS JOIN ARTICULOS USING (COD_ARTICULO)
WHERE CATEGORIA LIKE 'Segunda'),
'Tercera',
(SELECT AVG (UNIDADES_VENDIDAS) *2
FROM VENTAS JOIN ARTICULOS USING(COD_ARTICULO)
WHERE CATEGORIA LIKE 'Tercera')
)
FROM ARTICULOS);

/*EJ 17*/
DELETE FROM TIENDAS WHERE COD_TIENDA NOT IN 
(SELECT DISTINCT COD_TIENDA FROM VENTAS);

/*EJ 18*/
DELETE FROM PEDIDOS
WHERE COD_ARTICULO IN 
(SELECT COD_ARTICULO
FROM FABRICANTES JOIN ARTICULOS USING (COD_FABRICANTE)
WHERE PAIS= 'BELGICA' AND CATEGORIA='Primera');
