/*EJ1*/
SELECT CODPRODUCTO, DENOMINACION, TIPO, PVP, STOCK
FROM PRODUCTOS WHERE TIPO='A' AND PVP>20;
/*EJ 2*/
SELECT TIPO, COUNT(*) FROM PRODUCTOS GROUP BY TIPO;
/*EJ 3*/
SELECT CODPRODUCTO, DENOMINACION FROM PRODUCTOS
WHERE CODPRODUCTO NOT IN (SELECT CODPRODUCTO FROM DETCOMPRAS);
/*EJ 4*/
SELECT DISTRICT CODCLIENTE, NOMBRE
FROM CLIENTES JOIN COMPRAS USING (CODCLIENTE)
JOIN DETCOMPRAS USING (NUMCOMPRA) JOIN PRODUCTOS USING (CODPRODUCTO)
WHERE POBLACION='MADRID' AND TIPO='A' ORDER BY 1;
/*EJ 5*/
SELECT DISTRICT CODPRODUCTO, DENOMINACION, TIPO,
PVP, STOCKFROM PRODUCTOS FROM PRODUCTOS JOIN DETCOMPRAS USING(CODPRODUCTOS)
JOIN COMPRAS USING (NUMCOMPRA) JOIN CLIENTES USING (CODCLIENTE)
WHERE POBLACION;
/*EJ 6*/
SELECT NUMCOMPRA, FECHA, CODCLIENTE, NOMBRE
FROM CLIENTES JOIN COMPRAS USING (CODCLIENTE)
WHERE POBLACION='MADRID' AND TO_CHAR(FECHA,Q)= 1 ORDER BY 1,3;
/*EJ 8*/
SELECT DISTRICT CODPRODUCTO, DENOMINACION. TIPO, PVP,
SUM(UNIDADES), PVP *SUM(UNIDADES), STOCK, STOCK-SUM(UNIDADES)
FROM PRODUCTOS JOIN DETCOMPRAS USING (CODPRODUCTO)
GROUP BY CODPRODUCTO, DENOMINACION, TIPO, PVP, STOCK ORDER BY 1;
/*EJ 9*/
SELECT CODPRODUCTO, DENOMINACION, TIPO, PVP
FROM PRODUCTOS JOIN DETCOMPRAS USING (CODPRODUCTO)
GROUP BY CODPRODUCTO, DENOMINACION, TIPO, PVP, STOCK
HAVING (STOCK- SUM(UNIDADES)<=0)
ORDER BY 1;
/*EJ 10*/
SELECT DISTRICT CODCLIENTE, NOMBRE, CODPRODUCTO, DENOMINACION
FROM CLIENTES JOIN COMPRAS USING (CODPRODUCTO)
WHERE PVP=(SELECT MIN(PVP) FROM PRODUCTOS) ORDER BY 1;
/*EJ 11*/
SELECT CODPRODUCTO, DENOMINACION, TIPO, PVP, SUM(UNIDADES)
FROM PRODUCTOS JOIN DERCOMPRAS USING (CODPRODUCTO)
GROUP BY CODPRODUCTO, DENOMINACION, TIPO, PVP
HAVING SUM(UNIDADES)=(SELECT MAX(SUM(UNIDADES))
FROM PRODUCTOS JOIN DETCOMPRAS USING (CODPRODUCTO)
GROUP BY CODPRODUCTO)
ORDER BY CODPRODUCTO;
