/*NOS DA EL NOMBRE DE LOS JUEGOS LOS CUALES LA DURACION ES MAYOR QUE CUALQUIER DURACION DE UN JUEGO 
CUYA DURACION SEA MAYOR QUE 10 Y SEA DE UN JUGADOR*/
SELECT NOMBRE
FROM JUEGOS
WHERE DURACION > ANY(SELECT DURACION FROM JUEGOS WHERE DURACION >10
GROUP BY DURACION, TIPO HAVING TIPO LIKE 'Un jugador');
/*NOS DA LOS NOMBRES DE LOS JUGADORES EN LOS QUE LA PROVINCIA ES SEVILLA Y MIENTRAS QUE EXISTA UNA EDAD 
DE LOS JUGADORES DONDE PROVINCIA SEA TOLEDO*/
SELECT NOMBRE 
FROM JUGADORES 
WHERE PROVINCIA LIKE 'Sevilla' AND  EXISTS(SELECT EDAD FROM JUGADORES WHERE TRIM(PROVINCIA) LIKE 'Toledo');
/*NOS DA EL NOMBRE DE LA COMPETICIONES CREADAS EN EL 2023 Y TENGA UN CODIGO CUYO NOMBRE DE LA 
COMPETICION EMPIECE POR EVO*/
SELECT NOMBRE
FROM COMPETICIONES 
WHERE FECHA_COMPETICIÓN >= '01/01/23' AND FECHA_COMPETICIÓN <= '31/12/23' AND COD_COMPETICIÓN IN 
(SELECT COD_COMPETICIÓN FROM COMPETICIONES WHERE NOMBRE LIKE('EVO%'));
/*NOS DA EL NOMBRE Y LOS PUNTOS DE LOS LOGROS CUYOS PUNTOS SENA MAYORES QUE LOS PUNTOS DE LOS LOGROS MENORES 
O IGUALES A 20 Y NO EXISTA LA CONSULTA EN EL CUAL LOS PUNTOS SEAN 70*/
SELECT NOMBRE, PUNTOS
FROM LOGROS
WHERE PUNTOS > ALL(SELECT PUNTOS FROM LOGROS WHERE PUNTOS <= 20 AND NOT EXISTS
(SELECT PUNTOS FROM LOGROS WHERE PUNTOS =70));
/*NOS DA EL NOMBRE, EDAD Y DNI DE LOS JUGADORES LOS CUALES TENGAN EDAD SIEMPRE Y CUANDO EXISTA
UN JUGADOR CON 18 AÑOS Y EL CORREO EMPIECE POR J*/
SELECT DNI, NOMBRE, EDAD
FROM JUGADORES
WHERE EDAD IN (SELECT EDAD FROM JUGADORES WHERE EXISTS(SELECT EDAD FROM JUGADORES WHERE EDAD=18))
AND CORREO LIKE 'J%';