/*NOS MUESTRA EL NOMBRE DE LOS JUEGOS CON UN PRECIO MAYOR QUE EL MINIMO Y QUE SEAN PARA UN JUGADOR*/
SELECT NOMBRE 
FROM JUEGOS 
WHERE PRECIO > (SELECT MIN(PRECIO) FROM JUEGOS)
GROUP BY TIPO, NOMBRE
HAVING TIPO LIKE 'Un jugador';
/*NOS MUESTRA EL NICK DE LAS CUENTAS CON UNA FECHA DE CREACION ENTRE 20/11/2023 Y 10/12/2023,
ADEMAS SU DNI DEBE TERMINAR EN A*/
SELECT NICK"NOMBRE"
FROM CUENTAS
WHERE FECHA_CREACION >='20/11/2023' AND FECHA_CREACION <='10/12/2023'
GROUP BY NICK, DNI_JUG
HAVING dni_jug LIKE '%A'
ORDER BY NICK;
/*NOS MUESTRA EL NOMBRE DEL JUEGO Y SU PRECIO DE AQUELLOS CON CUENTEN CON LA DURACION MAXIMA Y 
TENGAN DE TIPO UN JUGADOR*/
SELECT NOMBRE "JUEGO", PRECIO
FROM JUEGOS 
WHERE DURACION = (SELECT MAX(DURACION) FROM JUEGOS)
GROUP BY NOMBRE, PRECIO, TIPO
HAVING TIPO LIKE 'Un jugador'
ORDER BY NOMBRE;
/*NOS MUESTRA LOS NOMBRES DE LOS LOGROS DE LOS JUEGOS CUYO CODIGO EMPIECE POR 1 Y 
CONTES DICHOS LOGROS DE 20 PUNTOS*/
SELECT NOMBRE 
FROM LOGROS
WHERE COD_JUEGO LIKE '1%'
GROUP BY NOMBRE, PUNTOS
HAVING PUNTOS = 20
ORDER BY NOMBRE;
/*NOS MUESTRA EL NOMBRE Y CORREO DE QUELLOS JUGADORES QUE PERTENEZCAN A LA PROVINCIA DE TOLEDO Y 
SU DNI TERMINE EN A*/
SELECT NOMBRE, CORREO
FROM JUGADORES
WHERE PROVINCIA LIKE 'Toledo'
GROUP BY NOMBRE, CORREO, DNI
HAVING DNI LIKE '%A'
ORDER BY NOMBRE;