--SET SERVEROUTPUT ON       --NECESARIO PARA PODER MOSTRAR LAS COSAS
--SET VERIFY OFF      --PARA DESACTIVAR QUE SE MUESTRE EL CODIGO
/*BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA MUNDO');
END;*/

/*DECLARE
    MI_NOMBRE VARCHAR(20):='&NOMBRE';
BEGIN
    DBMS_OUTPUT.PUT_LINE('HOLA ' || MI_NOMBRE);
END;*/

/*ACCEPT PREC NUMBER FORMAT '99.99' PROMPT 'Teclea un precio:'
ACCEPT UNID NUMBER FORMAT '99' PROMPT 'Teclea un unidades:'
ACCEPT IV NUMBER FORMAT '99.99' PROMPT 'Teclea un iva:'
DECLARE
    PRECIO NUMBER(4,2):=&PREC;
    UNIDADES NUMBER(3):=&UNID;
    IVA NUMBER(4,2):=&IV;
BEGIN
    DBMS_OUTPUT.PUT_LINE('El total es: '||
TO_CHAR((PRECIO*UNIDADES) + (PRECIO*UNIDADES*IVA)));
END;*/

/*BLOQUE OL/SQL QUE PERMITA ACTUALIZAR LA POBLACIÓN DE UN ALMACEN*/

/*
ACCEPT pob_ant PROMPT 'Introduce la población a modificar: ';
ACCEPT pob_new PROMPT 'Introduce la población nueva: ';
DECLARE
    pob_ant ALMACENES.POBLACION%TYPE:='&pob_ant';
    pob_new ALMACENES.POBLACION%TYPE:='&pob_new';
BEGIN 
    UPDATE ALMACENES SET POBLACION=POB_NEW
    WHERE UPPER(POBLACION)=UPPER(POB_ANT);
END;*/

/* BLOQUE DE PL/SWL QUE INSERTE UN NUEVO ALMACÉN*/

DECLARE 
R_ALMACEN ALMACENES%ROWTYPE;
BEGIN
    -- INICIALIZAR LOS CAMPOS DE R_ALMACÉN.
    SELECT MAX(CODALMA)+1 INTO R_ALMACEN.CODALMA FROM ALMACENES;
    R_ALMACEN.NOMBRE := 'Almacén ' || TO_CHAR(R_ALMACEN.CODALMA);
    R_ALMACEN.POBLACION := 'Talavera';
    R_ALMACEN.FACTURACION:=5000;
    
    INSERT INTO ALMACENES VALUES (R_ALMACEN.CODALMA,R_ALMACEN.NOMBRE,
                                                                            R_ALMACEN.POBLACION,R_ALMACEN.FACTURACION);
    DBMS_OUTPUT.PUT_LINE('REGISTRO INSERTADO CORRECTAMENTE');
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
END;