SET SERVEROUTPUT ON       
SET VERIFY OFF

/*AÑADIMOS UNA NUEVA FILA A LA TABLA CUENTAS_TIENEN_JUEGOS*/

DECLARE
    NNICK CUENTAS_TIENEN_JUEGOS.NICK%TYPE;
    FECHA CUENTAS_TIENEN_JUEGOS.FECHA_COMPRA%TYPE;
    COD CUENTAS_TIENEN_JUEGOS.COD_JUEGO%TYPE;
    INSERTA BOOLEAN:=TRUE;
    CONT NUMBER(1):=0;
BEGIN
    NNICK:='&NUEVO_NICK';
    COD:=&CODIGO_DEL_JUEGO;
    FECHA:='&FECHA_DE_CREACION';
    
    SELECT COUNT(*) INTO CONT FROM CUENTAS_TIENEN_JUEGOS WHERE COD_JUEGO=COD;
    
    IF CONT<=0 THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE ESE CODIGO DE JUEGO');
        INSERTA:=FALSE;
    END IF;
    
    IF INSERTA THEN
        INSERT INTO CUENTAS_TIENEN_JUEGOS VALUES (NNICK, COD, FECHA);
        DBMS_OUTPUT.PUT_LINE('HA SIDO INSERTADO');
    END IF;
    
    EXCEPTION
        When Dup_Val_On_Index Then
        Dbms_Output.Put_Line('Error, esa fila ya existe');
END;

/*MODIFICAMOS LA FECHA DE UNA DE LAS FILAS*/

DECLARE
NICKN CUENTAS_TIENEN_JUEGOS.NICK%TYPE;
FECHA CUENTAS_TIENEN_JUEGOS.FECHA_COMPRA%TYPE;
COD CUENTAS_TIENEN_JUEGOS.COD_JUEGO%TYPE;
CONT NUMBER(1):=0;
CORRECTO BOOLEAN:=TRUE;
BEGIN
NICKN:='&EL_NICK_DE_LA_CUENTA_EXISTENTE';
COD:=&EL_CODIGO_DEL_JUEGO;
FECHA:='&LA_NUEVA_FECHA';

SELECT COUNT(*) INTO CONT FROM CUENTAS_TIENEN_JUEGOS WHERE NICKN=NICK;

IF CONT<=0 THEN
    DBMS_OUTPUT.PUT_LINE('ESE NICK NO EXISTE');
    CORRECTO:=FALSE;
END IF;

SELECT COUNT(*) INTO CONT FROM JUEGOS WHERE COD=COD_JUEGO;

IF CONT<=0 THEN
    DBMS_OUTPUT.PUT_LINE('EL CODIGO NO EXISTE');
    CORRECTO:=FALSE;
END IF;

SELECT COUNT(*) INTO CONT FROM CUENTAS_TIENEN_JUEGOS WHERE COD=COD_JUEGO AND NICKN=NICK;
IF CONT<=0 THEN
    DBMS_OUTPUT.PUT_LINE('EL CODIGO Y EL NICK NO TIENEN RELACION');
    CORRECTO:=FALSE;
END IF;

IF CORRECTO THEN
    UPDATE CUENTAS_TIENEN_JUEGOS SET FECHA_COMPRA=FECHA
    WHERE NICKN LIKE NICK AND COD LIKE COD_JUEGO;
    DBMS_OUTPUT.PUT_LINE('SE HA ACTUALIZADO CORRECTAMENTE');
END IF;

END;