DROP TABLE CLIENTE;
DROP TABLE PRODUCTO;
DROP TABLE CLIENTE_COMPRA_PRODUCTO;
DROP TABLE PROVEDOR;

CREATE TABLE CLIENTE(
    RFC VARCHAR2(20),
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDOS VARCHAR2(40) NOT NULL,
    DIRECCION VARCHAR2(30) NOT NULL,
    FECHA_DE_NACIMIENTO VARCHAR2(40) NOT NULL,
    CONSTRAINT CLI_RFC_PK PRIMARY KEY(RFC)
);

CREATE TABLE PRODUCTO(
    NOMBRE VARCHAR2(20) NOT NULL,
    PRECIO NUMBER(5) NOT NULL,
    CODIGO NUMBER(4),
    CONSTRAINT PRO_COD_PK PRIMARY KEY(CODIGO)
);

CREATE TABLE CLIENTE_COMPRA_PRODUCTO(
    RFC_CLIENTE VARCHAR2(20),
    CODIGO_PRODUCTO NUMBER(4),
    CONSTRAINT CLI_PK PRIMARY KEY(RFC_CLIENTE, CODIGO_PRODUCTO),
    CONSTRAINT CLI_RFC_FK FOREIGN KEY(RFC_CLIENTE) REFERENCES CLIENTE ON DELETE CASCADE,
    CONSTRAINT CLI_COD_FK FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO ON DELETE CASCADE
);

CREATE TABLE PROVEDOR(
    RFC VARCHAR2(20),
    CODIGO_PRODUCTO NUMBER(4),
    NOMBRE VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR(30) NOT NULL,
    CONSTRAINT PRO_RFC_PK PRIMARY KEY(RFC),
    CONSTRAINT PRO_COD_FK FOREIGN KEY(CODIGO_PRODUCTO) REFERENCES PRODUCTO ON DELETE CASCADE
);

