DROP TABLE CLIENTE;
DROP TABLE PRODUCTO;
DROP TABLE PROVEDOR;

CREATE TABLE CLIENTE(
    RFC VARCHAR2(20),
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDOS VARCHAR2(40) NOT NULL,
    DIRECCION VARCHAR2(30) NOT NULL,
    FECHA_DE_NACIMIENTO VARCHAR2(40) NOT NULL,
    CONSTRAINT CLI_RFC_PK PRIMARY KEY(RFC)
);

CREATE TABLE PRODUCTO(
    NOMBRE VARCHAR2(20) NOT NULL,
    PRECIO NUMBER(5) NOT NULL,
    CODIGO NUMBER(4),
    CONSTRAINT PRO_COD_PK PRIMARY KEY(CODIGO)
);

CREATE TABLE PROVEDOR(
RFC VARCHAR2(20),
NOMBRE VARCHAR2(20) NOT NULL,
DIRECCION VARCHAR(30) NOT NULL,
CONSTRAINT PRO_RFC_PK PRIMARY KEY(RFC)
);