/* SCRIPT CREACIÓN MATRICULAS...
*/
DROP TABLE ALUMNOS CASCADE CONSTRAINTS;   -- bloque de borrado tablAS
DROP TABLE ASIGNATURAS CASCADE CONSTRAINTS;
DROP TABLE MATRICULAS CASCADE CONSTRAINTS;

CREATE TABLE ALUMNOS(
    Nombre VARCHAR2(20) NOT NULL, 
    Ape1 VARCHAR2(30) NOT NULL, 
    Ape2 VARCHAR2(30) DEFAULT 'SOLICITAR',    
    codigo NUMBER(4), 
    CONSTRAINT alu_cod_PK PRIMARY KEY(codigo),
    CONSTRAINT alu_cod_CK CHECK(codigo BETWEEN 2000 AND 4000));

INSERT INTO ALUMNOS VALUES ('Lidia','Amor','Pintado', 2001);
INSERT INTO ALUMNOS(Nombre, Ape1, codigo) VALUES ('Jose','Lopez',2002);
--INSERT INTO ALUMNOS(Nombre, codigo) VALUES ('Luis',2003);
--INSERT INTO ALUMNOS VALUES ('Pepe','Gonzalez',NULL, 1001);

CREATE TABLE ASIGNATURAS(
    Codigo NUMBER(4),
    Nombre VARCHAR2(20) NOT NULL, 
    Curso NUMBER(1) NOT NULL,
    CONSTRAINT asi_cod_PK PRIMARY KEY(Codigo),
    CONSTRAINT asi_cod_CK CHECK(Codigo BETWEEN 100 AND 200),
    CONSTRAINT asi_cur_CK CHECK(Curso BETWEEN 1 AND 2));
    
INSERT INTO ASIGNATURAS VALUES(100, 'BD',1);
INSERT INTO ASIGNATURAS VALUES(101,'PROG',1);
INSERT INTO ASIGNATURAS VALUES(102,'EIE',2);

CREATE TABLE MATRICULAS(
    Codigo_alu NUMBER(4),
    Codigo_asig NUMBER(4),
    CONSTRAINT mat_PK PRIMARY KEY(Codigo_alu, Codigo_asig),
    CONSTRAINT mat_alu_FK FOREIGN KEY(Codigo_alu) REFERENCES ALUMNOS ON DELETE CASCADE,
    CONSTRAINT mat_asi_FK FOREIGN KEY(Codigo_asig) REFERENCES ASIGNATURAS ON DELETE CASCADE
);

INSERT INTO MATRICULAS VALUES (2001,101);
INSERT INTO MATRICULAS VALUES (2001,100);
INSERT INTO MATRICULAS VALUES (2002,102);
INSERT INTO MATRICULAS VALUES (2002,100);

--DELETE FROM ALUMNOS WHERE codigo=2001;
--DELETE FROM ASIGNATURAS WHERE codigo=100;
--UPDATE ASIGNATURAS SET Codigo=150 WHERE Codigo=100;

ALTER TABLE ALUMNOS DROP (edad);

ALTER TABLE ALUMNOS ADD
    (edad NUMBER(3) DEFAULT 18 NOT NULL);
    
ALTER TABLE ALUMNOS MODIFY (Nombre VARCHAR2(10)); 
    
ALTER TABLE ALUMNOS RENAME COLUMN Ape1 TO Apellido1;
ALTER TABLE ALUMNOS RENAME COLUMN Ape2 TO Apellido2;
ALTER TABLE ALUMNOS RENAME COLUMN Codigo TO Codigo_alumno; --No problemas en claves simples (probar en compuestas)

ALTER TABLE ALUMNOS DROP CONSTRAINT alu_cod_CK;

    INSERT INTO ALUMNOS VALUES ('Lidia2','Amor2','Pintador2',6001,18);
    