/* */
DROP TABLE ALUMNO CASCADE CONSTRAINTS;
DROP TABLE ASIGNATURAS CASCADE CONSTRAINTS;
DROP TABLE MATRICULA CASCADE CONSTRAINTS;

CREATE TABLE ALUMNO (
    DNI VARCHAR2(9),
    NOMBRE VARCHAR(20) NOT NULL,
    APE1 VARCHAR(30) NOT NULL,
    APE2 VARCHAR(30) NOT NULL,
    CONSTRAINT ALU_DNI_PK PRIMARY KEY(DNI));
    
INSERT INTO ALUMNO VALUES ('04863330Q','ALVARO','SERRADILLA','OTERO');
INSERT INTO ALUMNO VALUES ('00000000A','LUCAS','LOPEZ','FERNANDEZ');

CREATE TABLE ASIGNATURAS(
    CODIGO NUMBER (4),
    NOMBRE VARCHAR2(20) NOT NULL,
    CURSO NUMBER(1) NOT NULL,
    CONSTRAINT ASI_COD_PK PRIMARY KEY(CODIGO),
    CONSTRAINT ASI_COD_CK CHECK(CODIGO BETWEEN 1000 AND 2000),
    CONSTRAINT ASI_CUR_CK CHECK(CURSO BETWEEN 1 AND 3)
    );
    
INSERT INTO ASIGNATURAS VALUES(1000, 'BD', 1);
INSERT INTO ASIGNATURAS VALUES(1001,'PROG',1);
INSERT INTO ASIGNATURAS VALUES(1002,'AD',2);

CREATE TABLE MATRICULAS(
    DNI VARCHAR2(9),
    CODIGO NUMBER(4),
    CONSTRAINT MAT_PK PRIMARY KEY(DNI, CODIGO),
    CONSTRAINT MAT_DNI_FK FOREIGN KEY (DNI) REFERENCES ALUMNO,
    CONSTRAINT MAT_COD_FK FOREIGN KEY (CODIGO) REFERENCES ASIGNATURA
);

INSERT INTO MATRICULAS VALUES ('04863330Q',1000);
INSERT INTO MATRICULAS VALUES ('00000000A',1001);

DELETE FROM ASIGNATURAS WHERE CODIGO=1000;