
DROP TABLE LOGROS CASCADE CONSTRAINTS;
DROP TABLE CUENTAS_CONSIGUEN_LOGROS CASCADE CONSTRAINTS;
DROP TABLE PARTICIPACIONES CASCADE CONSTRAINTS;


CREATE TABLE LOGROS(
    NOMBRE VARCHAR(100) NOT NULL,
    PUNTOS NUMBER(3) NOT NULL,
    NUMERO NUMBER(10),
    COD_JUEGO NUMBER(10),
    CONSTRAINT LOG_PK PRIMARY KEY(NUMERO,COD_JUEGO),
    CONSTRAINT LOG_COD_FK FOREIGN KEY(COD_JUEGO)REFERENCES JUEGOS ON DELETE CASCADE
 );   
CREATE TABLE CUENTAS_CONSIGUEN_LOGROS(
NICK VARCHAR2(30),
NUMERO NUMBER(10),
COD_JUEGO NUMBER(10),
FECHA_LOGRO DATE  NOT NULL,
CONSTRAINT CON_PK PRIMARY KEY (COD_JUEGO,NUMERO,NICK),
CONSTRAINT CON_NIC_FK FOREIGN KEY(NICK)REFERENCES CUENTAS ON DELETE CASCADE,
CONSTRAINT CON_COD_FK FOREIGN KEY(NUMERO,COD_JUEGO)REFERENCES LOGROS ON DELETE CASCADE
);
CREATE TABLE COMPETICIÓN(
COD_COMPETICIÓN NUMBER(10),
NOMBRE VARCHAR2(30) NOT NULL,
FECHA_COMPETICIÓN DATE NOT NULL,
CONSTRAINT COM_COD_PK PRIMARY KEY (COD_COMPETICIÓN)
);
CREATE TABLE PARTICIPACIONES(
DNI VARCHAR2(9),
COD_COMPETICIÓN NUMBER(10),
COD_JUEGO NUMBER(10),
PUESTO NUMBER(3) NOT NULL,
CONSTRAINT PAR_PK PRIMARY KEY (DNI,COD_COMPETICIÓN,COD_JUEGO),
CONSTRAINT PAR_DNI_FK FOREIGN KEY (DNI)REFERENCES JUGADORES ON DELETE CASCADE,
CONSTRAINT PAR_COM_FK FOREIGN KEY(COD_COMPETICIÓN)REFERENCES COMPETICIÓN ON DELETE CASCADE,
CONSTRAINT PAR_COD_FK FOREIGN KEY (COD_JUEGO)REFERENCES JUEGOS ON DELETE CASCADE
);

INSERT INTO TO LOGROS